version: '3'
services:

  percona:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: "simpleRootPasswd5"
    restart: always
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "simpleRootPasswd5"
    links:
      - percona:db
    ports:
      - "8080:80"
    restart: always

  mongodb:
    image: mongo:3.6.7
    ports:
      - "27017:27017"

  postgres:
    image: postgres:10.11
    restart: always
    environment:
      POSTGRES_PASSWORD: simpleRootPasswd5
      POSTGRES_USER: develop
      POSTGRES_DB: develop
    ports:
      - "5432:5432"
