version: '3'
services:

  percona:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: "simpleRootPasswd5"
    restart: "no"
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "simpleRootPasswd5"
    links:
      - percona:db
    ports:
      - "8080:80"
    restart: "no"

  mongodb:
    image: mongo:3.6.7
    ports:
      - "27017:27017"

  postgres:
    image: postgres:10.11
    restart: "no"
    environment:
      POSTGRES_PASSWORD: simpleRootPasswd5
      POSTGRES_USER: develop
      POSTGRES_DB: develop
    ports:
      - "5432:5432"

  memcached:
    image: memcached:1.5.22
    restart: "no"
    ports:
      - "11211:11211"

  redis:
    image: redis:5.0.7
    restart: "no"
    ports:
      - "6379:6379"
