start_mongo:
	docker-compose up -d mongodb

start_percona:
	docker-compose up -d percona

start_percona8:
	docker-compose up -d percona8

start_pma:
	docker-compose up -d pma

start_postgres:
	docker-compose up -d postgres

start_memcached:
	docker-compose up -d memcached

start_redis:
	docker-compose up -d redis

start_prometheus:
	docker-compose up -d prometheus

start_grafana:
	docker-compose up -d grafana
